// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Xcode activation gets its administrator password: typed here, it runs over the bridge
 * with `sudo`; absent or blank, the guest Terminal opens and the user types it there.
 */
export type ActivateMacXcodeInput = { password: string | null };
