// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppleDeviceSummary = {
    id: string;
    name: string;
    udid: string;
    platform: string;
    status: string;
    deviceClass: string;
    model: string;
    addedDate: string;
};
