// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleIdAttributes = {
    identifier: string;
    name: string;
    platform: string;
    seedId: string | null;
};
