// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CertificateAttributes = {
    certificateContent: string | null;
    name: string | null;
    displayName: string | null;
    certificateType: string | null;
    serialNumber: string | null;
    platform: string | null;
    expirationDate: string | null;
};
