// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the console session ended. Each of these is a run that happened, not a failure.
 */
export type ConsoleEnd = 'stopped' | 'exited' | 'disconnected';
