// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppleProvisioningProfileSummary } from './AppleProvisioningProfileSummary';
import type { SigningKitSummary } from './SigningKitSummary';

export type DownloadAppleProfileResult = {
    profile: AppleProvisioningProfileSummary;
    savedPath: string;
    kit: SigningKitSummary;
};
