// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVariableInput } from './EnvVariableInput';

export type EnvSetInput = {
    /**
     * Absent creates a set; present updates that set in place.
     */
    setId: string | null;
    name: string;
    /**
     * The complete variable list: a stored key that is not listed is removed.
     */
    variables: Array<EnvVariableInput>;
};
