// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One variable as the interface shows it, value included.
 */
export type EnvVariableSummary = { key: string; value: string };
