// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptimizationTier } from './OptimizationTier';

/**
 * One optimization as the interface shows it: the catalogue entry plus whether the guest
 * already has it, when the guest can be asked.
 */
export type GuestOptimizationView = {
    /**
     * `None` when the guest cannot be asked right now, or the check could not tell.
     */
    applied: boolean | null;
    id: string;
    title: string;
    summary: string;
    tier: OptimizationTier;
    /**
     * The caveat, in the source's words where it gives one.
     */
    warning: string | null;
    needsAdmin: boolean;
};
