// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MachineTemplateSummary = {
    id: string;
    name: string;
    createdAtEpochSeconds: number;
    sourceMachineName: string;
    macosVersion: string | null;
    xcodeVersion: string | null;
    sizeBytes: number;
    /**
     * Machines cloned from it. While any exists the template cannot be deleted, since their
     * disks read through it.
     */
    machineNames: Array<string>;
    /**
     * The files are all present; a save that stopped halfway leaves this false.
     */
    ready: boolean;
};
