// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacBuilderView } from './MacBuilderView';

export type PrepareDeviceSigningResult = {
    view: MacBuilderView;
    certificateCreated: boolean;
    deviceAlreadyRegistered: boolean;
    profileCreated: boolean;
};
