// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelationshipList } from './RelationshipList';

export type ProfileRelationships = {
    devices: RelationshipList | null;
    certificates: RelationshipList | null;
};
