// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppleArchiveResult } from './AppleArchiveResult';
import type { MacBuilderView } from './MacBuilderView';

export type RunAppleArchiveResult = { view: MacBuilderView; archive: AppleArchiveResult };
