// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppleDeviceRunResult } from './AppleDeviceRunResult';
import type { MacBuilderView } from './MacBuilderView';

export type RunAppleDeviceResult = { view: MacBuilderView; run: AppleDeviceRunResult };
