// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunState } from './RunState';

export type RunOnceResult = { state: RunState; buildId: string | null; message: string };
