// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What opening Safari for the Web Inspector found in the guest.
 */
export type SafariInspectorResult = {
    /**
     * Safari's Develop menu is on, so the phone and its inspectable pages appear under it.
     */
    developMenuEnabled: boolean;
    /**
     * Safari was running with the menu off and was reopened so the menu appears.
     */
    safariRestarted: boolean;
};
