// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppleDeviceRunResult } from './AppleDeviceRunResult';

export type StoredAppleDeviceRun = {
    containerId: string;
    snapshotSha256: string;
    deviceIdentifier: string;
    result: AppleDeviceRunResult;
    finishedAtEpochSeconds: number;
};
