// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredEnvVariable } from './StoredEnvVariable';

export type StoredEnvSet = {
    id: string;
    name: string;
    variables: Array<StoredEnvVariable>;
    createdAtEpochSeconds: number;
};
