// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoredMachineTemplate = {
    id: string;
    name: string;
    createdAtEpochSeconds: number;
    sourceMachineName: string;
    macosVersion: string | null;
    xcodeVersion: string | null;
    guestUsername: string;
    /**
     * The guest's SSH host key as pinned on the source machine. A clone boots with the same
     * key, which is how it is recognised.
     */
    knownHostsLine: string;
    sizeBytes: number;
};
