// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which SDK the unsigned test build compiles against. The device SDK ships inside Xcode and is
 * what a signed archive and a device run use, so it needs nothing downloaded; the Simulator is
 * the only target that can be run on screen inside the guest, and Xcode lacks its runtime until
 * Apple's iOS platform — several gigabytes — has been downloaded.
 */
export type UnsignedBuildTarget = 'device_sdk' | 'simulator';
