// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppleProjectPhase =
    | 'snapshotting'
    | 'transferring'
    | 'extracting'
    | 'preparing_tools'
    | 'preparing_platform'
    | 'installing_dependencies'
    | 'building_web_assets'
    | 'syncing_ios'
    | 'resolving_pods'
    | 'building'
    | 'completed';
