// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppleArchivePhase =
    | 'preparing'
    | 'building_web_assets'
    | 'archiving'
    | 'exporting'
    | 'verifying'
    | 'packaging_archive'
    | 'transferring'
    | 'completed';
