// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppleDeviceRunPhase } from './AppleDeviceRunPhase';

/**
 * Progress carries every console line since the last event rather than the latest one: an
 * app console must not drop lines between ticks the way filtered build output may.
 */
export type AppleDeviceRunProgress = {
    phase: AppleDeviceRunPhase;
    elapsedSeconds: number;
    detail: string;
    logLines: Array<string>;
};
