// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerRebuildPhase } from './ContainerRebuildPhase';

export type ContainerRebuildProgress = {
    phase: ContainerRebuildPhase;
    elapsedSeconds: number;
    detail: string;
};
