// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionProperties } from './ConnectionProperties';
import type { DeviceProperties } from './DeviceProperties';
import type { HardwareProperties } from './HardwareProperties';

export type DevicectlDevice = {
    identifier: string;
    hardwareProperties: HardwareProperties | null;
    deviceProperties: DeviceProperties | null;
    connectionProperties: ConnectionProperties | null;
};
