// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskMigrationPhase =
    | 'checking_space'
    | 'stopping'
    | 'copying_disk'
    | 'removing'
    | 'creating'
    | 'starting'
    | 'completed';
