// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuestDiagnostics = {
    authenticated: boolean;
    macosVersion: string | null;
    xcodeVersion: string | null;
    xcodePath: string | null;
    xcodeSelected: boolean;
    /**
     * The iOS Simulator runtime version the guest holds, when Xcode is ready and one is installed.
     */
    iosSimulatorRuntime: string | null;
    issue: string | null;
};
