// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptimizationTier } from './OptimizationTier';

/**
 * One tweak from sickcodes/osx-optimizer as BuildBridge can run it: a fixed script for the
 * guest, a check that reports whether it is already in effect, and the caveat the source gives.
 * Admin tweaks run in the guest's own Terminal, where `sudo` reads the password from its TTY;
 * BuildBridge never sees it.
 */
export type GuestOptimization = {
    id: string;
    title: string;
    summary: string;
    tier: OptimizationTier;
    /**
     * The caveat, in the source's words where it gives one.
     */
    warning: string | null;
    needsAdmin: boolean;
};
