// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HardwareProperties = {
    udid: string | null;
    platform: string | null;
    marketingName: string | null;
    productType: string | null;
};
