// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostUsbDevice } from './HostUsbDevice';
import type { UdevRuleState } from './UdevRuleState';

export type HostUsbStatus = {
    supported: boolean;
    rule: UdevRuleState;
    rulePath: string;
    usbmuxdActive: boolean;
    plugdevGid: number | null;
    devices: Array<HostUsbDevice>;
    issues: Array<string>;
};
