// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchPhase =
    | 'preparing'
    | 'pulling_image'
    | 'generating_identity'
    | 'preparing_disk'
    | 'creating_container'
    | 'starting'
    | 'completed';
