// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacOsRelease } from './MacOsRelease';

export type MacBuilderConfig = {
    name: string;
    macosRelease: MacOsRelease;
    memoryGib: number;
    cpuCores: number;
    sshPort: number;
};
