// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a profile is for, read from its entitlements rather than from a name. The plist has no
 * explicit type; the combination of `get-task-allow`, `ProvisionedDevices`, and
 * `ProvisionsAllDevices` is unambiguous.
 */
export type ProfileKind = 'app_store' | 'development' | 'ad_hoc' | 'enterprise';
