// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigningProvisioningPhase } from './SigningProvisioningPhase';

export type SigningProvisioningProgress = {
    phase: SigningProvisioningPhase;
    completedBytes: number;
    totalBytes: number;
    elapsedSeconds: number;
    detail: string;
};
