// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SigningProvisioningPhase =
    | 'creating_certificate'
    | 'creating_profile'
    | 'preparing'
    | 'transferring'
    | 'importing_certificate'
    | 'inspecting_profiles'
    | 'installing_profiles'
    | 'verifying'
    | 'completed';
