// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvisionedIdentity } from './ProvisionedIdentity';
import type { ProvisioningProfileSummary } from './ProvisioningProfileSummary';

/**
 * The stored shape, old and new. Records written before the distribution identity became
 * optional carried its four fields at the top level; they still read.
 */
export type SigningProvisioningWire = {
    keychainPath: string;
    distributionIdentity: ProvisionedIdentity | null;
    identityName: string | null;
    identitySha1: string | null;
    certificateSha256: string | null;
    certificateExpiresAt: string | null;
    developmentTeam: string;
    bundleIdentifier: string;
    profiles: Array<ProvisioningProfileSummary>;
    developmentIdentity: ProvisionedIdentity | null;
};
