// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XcodeImportPhase } from './XcodeImportPhase';

export type XcodeImportProgress = {
    phase: XcodeImportPhase;
    transferredBytes: number;
    totalBytes: number;
    elapsedSeconds: number;
    detail: string;
};
