#!/usr/bin/env node
// Regenerates src/types/generated from the Rust DTOs. Every serde type in the three native
// crates derives ts-rs's TS with `#[ts(export)]`, so `cargo test` writes one file per type into
// TS_RS_EXPORT_DIR; this script points that at the desktop, clears what was there first so a
// renamed type leaves no stale file, and writes the index the desktop imports through.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const desktop = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const workspace = resolve(desktop, '..', '..');
const target = resolve(desktop, 'src/types/generated');

rmSync(target, { recursive: true, force: true });
mkdirSync(target, { recursive: true });
execFileSync(
    'cargo',
    [
        'test',
        '-p',
        'buildbridge-contract',
        '-p',
        'buildbridge-docker-osx',
        '-p',
        'buildbridge-engine',
        'export_bindings',
    ],
    { cwd: workspace, stdio: 'inherit', env: { ...process.env, TS_RS_EXPORT_DIR: target } },
);

const names = readdirSync(target)
    .filter((file) => file.endsWith('.ts') && file !== 'index.ts')
    .map((file) => file.slice(0, -3))
    .sort();
const index = [
    '// Generated by scripts/generate-types.mjs from the Rust DTOs; do not edit by hand.',
    ...names.map((name) => `export type { ${name} } from './${name}';`),
    '',
].join('\n');
writeFileSync(resolve(target, 'index.ts'), index);
console.log(`${names.length} types written to ${target}`);
