// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppleProvisioningProfileSummary = {
    id: string;
    name: string;
    platform: string;
    profileType: string;
    profileState: string;
    uuid: string;
    createdDate: string;
    expirationDate: string;
    /**
     * Filled for development and ad hoc profiles when the memberships were fetched.
     */
    deviceUdids: Array<string>;
    certificateIds: Array<string>;
};
