// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleEnd } from './ConsoleEnd';
import type { GuestDevice } from './GuestDevice';

export type AppleDeviceRunResult = {
    device: GuestDevice;
    /**
     * The identifier the app was signed and installed under.
     */
    bundleIdentifier: string;
    /**
     * The project's own Debug identifier, when the build was signed under the approved one
     * instead because only that one has a development profile.
     */
    projectBundleIdentifier: string | null;
    appPath: string;
    marketingVersion: string;
    buildNumber: string;
    provisioningProfileUuid: string;
    installedAtEpochSeconds: number;
    consoleEnd: ConsoleEnd;
    exitStatus: number | null;
    reattached: boolean;
    buildTail: Array<string>;
    consoleTail: Array<string>;
};
