// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachedUsbDevice = {
    bus: number;
    port: string;
    /**
     * The guest has enumerated the phone; until then QEMU holds only the port.
     */
    enumerated: boolean;
    issue: string | null;
};
