// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundleIdAttributes } from './BundleIdAttributes';

export type BundleIdResource = { id: string; attributes: BundleIdAttributes };
