// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvVariableInput = {
    key: string;
    /**
     * `None` keeps the value already stored under this key.
     */
    value: string | null;
    /**
     * Masked in the interface and left out of every summary once stored.
     */
    secret: boolean;
};
