// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuestTrustState } from './GuestTrustState';

export type GuestSshStatus = {
    portOpen: boolean;
    reachable: boolean;
    trust: GuestTrustState;
    fingerprint: string | null;
    pinnedFingerprint: string | null;
    issue: string | null;
};
