// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The part of a heartbeat reply the interface acts on.
 */
export type HeartbeatSummary = {
    /**
     * Work waiting for this runner. Non-zero means a queue event was missed; claim now.
     */
    queuedBuilds: number;
};
