// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsbHolder } from './UsbHolder';

export type HostUsbDevice = {
    bus: number;
    /**
     * The sysfs `devpath`, which is also what QEMU calls `hostport`.
     */
    port: string;
    vendorId: string;
    productId: string;
    product: string | null;
    serial: string | null;
    manufacturer: string | null;
    deviceNode: string;
    /**
     * This user can open the node read-write, which is exactly what the container's QEMU
     * user (the same uid, plus the plugdev group) needs.
     */
    nodeReady: boolean;
    heldBy: UsbHolder | null;
};
