// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostPrerequisites = {
    supportedHost: boolean;
    dockerCli: boolean;
    dockerDaemon: boolean;
    dockerVersion: string | null;
    kvmAccess: boolean;
    displayAccess: boolean;
    display: string | null;
    ready: boolean;
    issues: Array<string>;
};
