// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuestDevice } from './GuestDevice';
import type { GuestDiagnostics } from './GuestDiagnostics';
import type { GuestSshStatus } from './GuestSshStatus';

export type MacGuestAccessView = {
    username: string | null;
    publicKey: string | null;
    ssh: GuestSshStatus;
    diagnostics: GuestDiagnostics;
    /**
     * The phones the guest saw at its last listing; empty until one is requested.
     */
    devices: Array<GuestDevice>;
};
