// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerState } from './ContainerState';
import type { MacBuilderConfig } from './MacBuilderConfig';

export type MachineSummary = {
    id: string;
    config: MacBuilderConfig;
    createdAtEpochSeconds: number;
    state: ContainerState;
    containerId: string | null;
    busyOperation: string | null;
    guestConfigured: boolean;
    trustPinned: boolean;
    workspaceName: string | null;
    signingKitName: string | null;
    signingProvisioned: boolean;
    signingIdentity: string | null;
    archiveRetained: boolean;
    envSetName: string | null;
    /**
     * The container keeps its disk on the host and can be handed USB devices.
     */
    usbReady: boolean;
    deviceRunRetained: boolean;
    /**
     * The template this machine was cloned from, if any.
     */
    templateName: string | null;
};
