// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostPrerequisites } from './HostPrerequisites';
import type { MachineSummary } from './MachineSummary';

export type MachineListView = { host: HostPrerequisites; machines: Array<MachineSummary> };
