// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A provisioning profile this host already downloaded, kept so a kit can be rebuilt without
 * going back to Apple. Only the file name and path are exposed; the contents stay on disk.
 */
export type ManagedAppleProfile = { fileName: string; path: string; savedAtEpochSeconds: number };
