// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileAttributes = {
    name: string | null;
    platform: string | null;
    profileType: string | null;
    profileState: string | null;
    uuid: string | null;
    createdDate: string | null;
    expirationDate: string | null;
    profileContent: string | null;
};
