// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigningProvisioningResult } from './SigningProvisioningResult';

export type StoredSigningProvisioning = { containerId: string; result: SigningProvisioningResult };
