// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredSigningKit } from './StoredSigningKit';

export type StoredSigningKits = { kits: Array<StoredSigningKit> };
