// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named set of environment variables for a build, held in the host's vault like a signing
 * kit and attached per machine. A plain variable's value is shown back in the interface; a
 * secret's is left out of every summary and comes back only to the editor, on request.
 */
export type StoredEnvVariable = {
    key: string;
    value: string;
    /**
     * Masked in the interface and left out of every summary; `reveal_env_secrets` hands a set's
     * secrets to the editor on request. Sets stored before the distinction existed were promised
     * their values would not be shown, so a missing flag reads as a secret.
     */
    secret: boolean;
};
