// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildKind } from './BuildKind';
import type { JsonValue } from './serde_json/JsonValue';

export type ClaimedBuild = {
    id: string;
    kind: BuildKind;
    payload: JsonValue;
    lease_expires_at: string;
    next_log_sequence: number;
};
