// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the control plane says back to a heartbeat. `queued_builds` is the recovery path for a
 * missed queue event: the heartbeat is sent anyway, so carrying the count costs nothing, and a
 * runner that sees work waiting claims it instead of waiting for a broadcast that never came.
 */
export type HeartbeatResponse = {
    protocol_version: number;
    server_time: string;
    /**
     * Builds queued for this runner, or running on a lease that has lapsed.
     */
    queued_builds: number;
};
