// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunnerIdentity } from './RunnerIdentity';

export type PairRunnerResponse = {
    protocol_version: number;
    runner: RunnerIdentity;
    token: string;
};
